# Generated by Django 3.2.16 on 2022-10-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bb_options_bb_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='contacts',
        ),
    ]
