# Generated by Django 3.2.16 on 2022-10-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_bb_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='price',
        ),
    ]
