# Generated by Django 4.1.2 on 2022-10-29 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_bb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='last_name',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric', regex='[а-яА-ЯёЁ]')], verbose_name='Фамилия'),
        ),
    ]
