# Generated by Django 4.1.2 on 2022-10-29 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_advuser_first_name_alter_advuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Имя пользователя введено не правильно', regex='^[a-z]+$')], verbose_name='Имя пользователя'),
        ),
    ]
