# Generated by Django 4.1.2 on 2022-10-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_advuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь'), ('author', 'Автор')], default='user', max_length=254, verbose_name='Роль'),
        ),
    ]
